# -*- coding: utf-8 -*-
"""Desafío-FunciónAñoBisiesto_Misael_OrtegaCruz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yD1C68-9fKxLF7fWtIYrOxSTWxyJClLe

**DESAFÍO FUNCIÓN AÑO BISIESTO**

(USAR ESTA PLANTILLA PARA ENTREGAR EL DESAFÍO POR FAVOR)


>> **Consigna: Realizar una función llamada año_bisiesto:**

Recibirá un año por parámetro.
Imprimirá “El año año es bisiesto” si el año es bisiesto.

Imprimirá “El año año no es bisiesto” si el año no es bisiesto.

Si se ingresa algo que no sea número debe indicar que se ingrese un número.



*Información a tener en cuenta:

Se recuerda que los años bisiestos son múltiplos de 4, pero los múltiplos de 100 no lo son, aunque los múltiplos de 400 sí. Estos son algunos ejemplos de posibles respuestas: 2012 es bisiesto, 2010 no es bisiesto, 2000 es bisiesto, 1900 no es bisiesto.
"""

print ("Este programa le permitirá conocer si un año es, ha sido, o será bisiesto. En caso de que lo necesite")


año =  0
def anobis(año):
    while True:
        año = input("Ingrese el año:\n")
        if año.isnumeric():
            añob = int(año)
            if añob%4 == 0 and añob%100 != 0:
                print (f'{añob} es bisiesto')
                break
            elif añob%4 == 0 and añob%100 == 0 and añob%400 == 0:
                print (f'{añob} es bisiesto')
                break
            else:
                print (f'{añob} no es bisiesto')
                break           
        else:
            print (f'El dato ingresado no es un número, por favor ingresa un número')
        
anobis (año)