# Generated by Django 3.2.15 on 2022-09-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='suennos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suenno', models.CharField(max_length=500)),
                ('pseudonimo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
