# Generated by Django 3.2.15 on 2022-09-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_suennos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suennos',
            new_name='sueños',
        ),
        migrations.RenameField(
            model_name='sueños',
            old_name='suenno',
            new_name='sueño',
        ),
    ]
