# Generated by Django 3.2.15 on 2022-09-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_auto_20220915_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='suenios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suenio', models.CharField(max_length=100)),
                ('pseudonimo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='sueños',
        ),
    ]
